const tabsMock = [
  {
    list: {
      tabsCode: 1,
      tabsName: "W1",
      conditionList: [
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "P01",
          conditionId: null,
          conditionName: "Professor",
          conditionPriority: 1,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "P02",
          conditionId: null,
          conditionName: "Consultant",
          conditionPriority: 1,
          ratioStatus: false,
          ratioValue: "0",
        },
      ],
    },
  },
  {
    list: {
      tabsCode: 2,
      tabsName: "W2",
      conditionList: [
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "1",
          conditionId: null,
          conditionName: "Hong Kong Resident",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "2",
          conditionId: null,
          conditionName: "Non-Hong Kong Resident",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
      ],
    },
  },
  {
    list: {
      tabsCode: 3,
      tabsName: "W3",
      conditionList: [
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "1",
          conditionId: null,
          conditionName: "Elderly",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "2",
          conditionId: null,
          conditionName: "Non-Elderly",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
      ],
    },
  },
  {
    list: {
      tabsCode: 4,
      tabsName: "W4",
      conditionList: [
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "B4001",
          conditionId: null,
          conditionName: "4-Bed Room",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "B2001",
          conditionId: null,
          conditionName: "2-Bed Room",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "B1001",
          conditionId: null,
          conditionName: "1-Bed Room",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "V1001",
          conditionId: null,
          conditionName: "VIP Room",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "IRW1001",
          conditionId: null,
          conditionName: "Isolation",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "NNU1001",
          conditionId: null,
          conditionName: "NNU(Cot)",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "DAY001",
          conditionId: null,
          conditionName: "Day Ward",
          conditionPriority: 0,
          ratioStatus: false,
          ratioValue: "0",
        },
      ],
    },
  },
  {
    list: {
      tabsCode: 5,
      tabsName: "W5",
      conditionList: [
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "1",
          conditionId: null,
          conditionName: "Public Day",
          conditionPriority: 1,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "2",
          conditionId: null,
          conditionName: "Weekend",
          conditionPriority: 2,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "3",
          conditionId: null,
          conditionName: "Weekday",
          conditionPriority: 3,
          ratioStatus: false,
          ratioValue: "0",
        },
      ],
    },
  },
  {
    list: {
      tabsCode: 6,
      tabsName: "W6",
      conditionList: [
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "1",
          conditionId: null,
          conditionName: "Peak Time",
          conditionPriority: 1,
          ratioStatus: false,
          ratioValue: "0",
        },
        {
          billAdjustStatus: false,
          billAdjustValue: "0",
          conditionCode: "2",
          conditionId: null,
          conditionName: "Non-Peak Time",
          conditionPriority: 2,
          ratioStatus: false,
          ratioValue: "0",
        },
      ],
    },
  },
];

export default tabsMock;
